/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeread_reset_com_nativeread_NativeHelper */

#ifndef _Included_nativeread_reset_com_nativeread_NativeHelper
#define _Included_nativeread_reset_com_nativeread_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeread_reset_com_nativeread_NativeHelper
 * Method:    SetAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_nativeread_reset_com_nativeread_NativeHelper_SetAssetManager
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
