/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class nativeread_reset_com_nativeread_NativeHelper */

#ifndef _Included_nativeread_reset_com_nativeread_NativeHelper
#define _Included_nativeread_reset_com_nativeread_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeread_reset_com_nativeread_NativeHelper
 * Method:    SetAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_nativeread_reset_com_nativeread_NativeHelper_SetAssetManager
        (JNIEnv *, jobject, jobject);

JNIEXPORT int32_t JNICALL ReadAssetsBytes
        (char* fileName, unsigned char** result);

JNIEXPORT int32_t JNICALL ReadAssetsBytesWithOffset
        (char* fileName, unsigned char** result, int32_t offset, int32_t length);

#ifdef __cplusplus
}
#endif
#endif
