/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndkdemo_reset_mytest_ndkdemo_NDKHelper */

#ifndef _Included_ndkdemo_reset_mytest_ndkdemo_NDKHelper
#define _Included_ndkdemo_reset_mytest_ndkdemo_NDKHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndkdemo_reset_mytest_ndkdemo_NDKHelper
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ndkdemo_reset_mytest_ndkdemo_NDKHelper_Add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
